baseURL = "https://jared-mac.github.io/"
title = "Jared Macshane"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
[params.profileMode]
  enabled = true
  title = "Jared Macshane"
  subtitle = "PhD Student in Computer Science at UC Irvine | Machine Learning & Systems Research"
  imageUrl = "/profile.jpg"
  imageTitle = "Jared Macshane"

[[params.profileMode.buttons]]
  name = "Publications"
  url = "/publications"

[[params.profileMode.buttons]]
  name = "Research"
  url = "/research"

[[params.profileMode.buttons]]
  name = "CV"
  url = "/cv"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 20

[[menu.main]]
  identifier = "publications"
  name = "Publications"
  url = "/publications/"
  weight = 30

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 40
